In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/00.이어드림/Project/FC Data analysis Project/데이터분석프로젝트_VER2_210329_210926.xlsx')
df.head()

,id,customer_id,course_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,tax_free_amount,pg,method,subcategory_title,marketing_start_at
0,970634.0,504760.0,201435.0,ORDER,CANCELLED,올인원 패키지 : 알고리즘 기술면접 완전 정복,프로그래밍,올인원,2021-03-28 15:00:11,90500.0,NaN,NaN,110500.0,110500.0,NaN,VBANK,개발자 커리어,NaT
1,970650.0,432862.0,203178.0,ORDER,CANCELLED,초격차 패키지 : 한번에 끝내는 영상 촬영과 편집,영상/3D,올인원,2021-03-28 15:16:53,96000.0,NaN,NaN,116000.0,116000.0,NaN,CARD,영상 편집,2020-12-02
2,970657.0,72297.0,204246.0,PAYMENT,COMPLETED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810.0,[10% 할인] 시크릿코드 실무 완성편,19090.0,190900.0,190900.0,NaN,CARD,NaN,2021-03-04
3,970656.0,72297.0,204246.0,ORDER,CANCELLED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810.0,NaN,NaN,190900.0,190900.0,NaN,CARD,NaN,2021-03-04
4,970658.0,478028.0,201797.0,PAYMENT,COMPLETED,올인원 패키지 : 직장인 필수 스킬 3종 세트 MAX,업무 생산성,올인원,2021-03-28 15:21:54,97500.0,[웰컴쿠폰] 올인원 패키지 2만원 할인 쿠폰,20000.0,117500.0,117500.0,NaN,CARD,PPT/보고서,2019-11-14

In [ ]:
# 테스트용 엑셀 데이터 뽑기
# df.drop(['id','course_id','customer_id','type','state','format','completed_at','transaction_amount','coupon_title','coupon_discount_amount','sale_price','tax_free_amount','pg','method','marketing_start_at'], axis=1, inplace=True)

# droplist = ['B2B','TEST','test','자유이용권']
# dropjoin = '|'.join(droplist)

# df = df[df["course_title"].str.contains(dropjoin) == False]

# df.to_excel(r'/content/drive/MyDrive/00.이어드림/Project/FC Data analysis Project\test222.xlsx', index = False)

In [ ]:
# 필요없는 column drop _ subcategory의 결측치 처리할 때만!
df.drop(['id','course_id','customer_id','type','state','format','completed_at','transaction_amount','coupon_title','coupon_discount_amount','sale_price','tax_free_amount','pg','method','marketing_start_at'], axis=1, inplace=True)
df.head()

                    course_title category_title subcategory_title
0      올인원 패키지 : 알고리즘 기술면접 완전 정복          프로그래밍           개발자 커리어
1    초격차 패키지 : 한번에 끝내는 영상 촬영과 편집          영상/3D             영상 편집
2           시크릿코드 : 프론트엔드 실무 완성편          프로그래밍               NaN
3           시크릿코드 : 프론트엔드 실무 완성편          프로그래밍               NaN
4  올인원 패키지 : 직장인 필수 스킬 3종 세트 MAX         업무 생산성           PPT/보고서

In [ ]:
df['course_title'].unique()

array(['올인원 패키지 : 알고리즘 기술면접 완전 정복', '초격차 패키지 : 한번에 끝내는 영상 촬영과 편집',
       '시크릿코드 : 프론트엔드 실무 완성편', ..., '(B2B) 그린오션스 온라인 구독 올 플랜 - 비대면바우처',
       '(B2B) 디캠프 패밀리사 온라인 구독 올 플랜 (9월)',
       '(B2B) (주)오디 온라인 구독 올 플랜 - 비대면바우처'], dtype=object)

In [ ]:
df['subcategory_title'].unique()

array(['개발자 커리어', '영상 편집', nan, 'PPT/보고서', '금융/투자 실무', '프론트엔드 개발',
       'DevOps', 'UX/UI', '머신러닝', '모션그래픽', '딥러닝/인공지능', '글쓰기/카피라이팅',
       '디지털마케팅', '엑셀/VBA', '데이터분석', '디자인툴', '모바일앱', '업무자동화', 'SNS마케팅',
       '게임', '회계/재무/세무', '부동산 개발', '시각디자인', '백엔드 개발', '데이터마케팅', '일러스트',
       '부동산 투자', '코딩 입문', '커뮤니케이션', '리더십', '주식 투자', '게임 그래픽', '데이터엔지니어링',
       'VFX'], dtype=object)

In [ ]:
# Course_title 조건 추출
# Course_title에 프론트라는 글자가 포함된 row들 추출 테스트

df.loc[df['course_title'].str.contains('프론트')==True]

,course_title,category_title,subcategory_title
2,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,NaN
3,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,NaN
14,초격차 패키지 : 한 번에 끝내는 프론트엔드 개발,프로그래밍,프론트엔드 개발
15,초격차 패키지 : 한 번에 끝내는 프론트엔드 개발,프로그래밍,프론트엔드 개발
30,올인원 패키지 : 프론트엔드 (React),프로그래밍,NaN
...,...,...,...
105284,The RED : 조은의 프론트엔드 실무 가이드 : 요구사항 분석과 적정 기술,프로그래밍,프론트엔드 개발
105293,초격차 패키지 : 한 번에 끝내는 프론트엔드 개발,프로그래밍,프론트엔드 개발
105307,프로모션 : 프론트엔드 맥북 pro 패스 (9월 현물 프리패스),프로그래밍,NaN
105311,프로모션 : 프론트엔드 맥북 pro 패스 (9월 현물 프리패스),프로그래밍,NaN
105379,초격차 패키지 : 한 번에 끝내는 프론트엔드 개발,프로그래밍,프론트엔드 개발

In [ ]:
# 결측치를 처리할 subcategory_title 추출

# 조건
# 1. 모든 Course_title을 기준으로 하여
# 2. Subcategory_title가 공백인 row들을 추출

# 설계 이유
# 모든 Couse_title을 기준으로 넣은 이유는
# 추후 모든 ⮕ 조건 을 기준으로 검색을 위한 필터링 조건을 설계

df= df.loc[(df['course_title'].str.contains('')==True)&(df['subcategory_title'].isnull())]
df

,course_title,category_title,subcategory_title
2,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,NaN
3,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,NaN
6,프로모션 : 2021 내 커리어 지켜 줄 UX/UI 디자인 한끝세트 (3월 프리패스),크리에이티브,NaN
10,올인원 패키지 : 권오상의 금융 아카데미 - 권오상의 재무제표 분석 기초(평생소장),부동산/금융,NaN
11,올인원 패키지 : 권오상의 금융 아카데미 - 권오상의 재무제표 분석 기초(평생소장),부동산/금융,NaN
...,...,...,...
105392,(B2B) K-Digital Credit 머신러닝 & AI 첫걸음 시작하기_6기,프로그래밍,NaN
105405,(B2B) K-Digital Credit Java & SpringBoot로 시작하는...,프로그래밍,NaN
105406,[한정판매] 자연어 A-Z 끝장 패키지(~9월),데이터사이언스,NaN
105408,프로모션 : 디자인 맥북 pro 패스(9월 현물 프리패스),디자인,NaN
105410,프로모션 : 풀스택 개발자 맥북 pro 패스(9월 현물 프리패스),프로그래밍,NaN

In [ ]:
# 의미가 없는 Course_title raw들 삭제를 위한 리스트 작성 테스트

# 개인에 대한 마케팅이 목표이기 때문에 B2B Raw Drop
# 그 이외에 FC에서 Test를 위해 사용한 데이터와
# 1개의 예외로 판단되는 자유이용권 raw drop

droplist = ['B2B','TEST','test','자유이용권']
dropjoin = '|'.join(droplist)
print(dropjoin)

B2B|TEST|test|자유이용권

In [ ]:
# Course_title에 droplist안에 있는 글자가 있는 raw가 있다면 해당 raw를 드랍
droplist = ['B2B','TEST','test','자유이용권']
dropjoin = '|'.join(droplist)


# 이후 head()를 통해 러프하게 확인
df = df[df["course_title"].str.contains(dropjoin) == False]
df.head()

,course_title,category_title,subcategory_title
2,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,NaN
3,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,NaN
6,프로모션 : 2021 내 커리어 지켜 줄 UX/UI 디자인 한끝세트 (3월 프리패스),크리에이티브,NaN
10,올인원 패키지 : 권오상의 금융 아카데미 - 권오상의 재무제표 분석 기초(평생소장),부동산/금융,NaN
11,올인원 패키지 : 권오상의 금융 아카데미 - 권오상의 재무제표 분석 기초(평생소장),부동산/금융,NaN

In [ ]:
## 딕셔너리를 사용하여 Course_title에 Key로 들어간 글자가 있고,
## Subcategory_title가 null값이라면,
## Subcategory_title에 Values값을 반환

# 맵핑 리스트 {Key : Values}
maplist= {
  '리팩터링':'개발자 커리어',
	'Top tier 프로젝트':'개발자 커리어',
	'주니어':'개발자 커리어',
  
  '프론트':'프론트엔드 개발',
  'React':'프론트엔드 개발',

  'DevOps':'DevOps',

  'iOS':'모바일앱',
	'AOS':'모바일앱',	

  'JPA':'백엔드 개발',
	'Spring':'백엔드 개발',
	'스프링':'백엔드 개발',
	'Java':'백엔드 개발',
	'Node':'백엔드 개발',

  '프로그래밍 입문':'코딩 입문',
	'프로그래밍 유치원':'코딩 입문',
	'클론':'코딩 입문',
	'알고리즘':'코딩 입문',
	'따라잡기' : '코딩 입문',

  '풀스텍':'웹개발',
	'풀스택':'웹개발',
	'웹 개발': '웹개발',
  
  '유튜브':'영상 편집',
	'유튜버':'영상 편집',

  'VFX' : 'VFX',

  '모션그래픽':'모션그래픽',
	'Render':'모션그래픽',
	'Financial':'금융/투자 실무',

  'PPT':'PPT/보고서',
	'기획서':'PPT/보고서',

  '업무자동화':'업무자동화',
	'직무 스킬':'업무자동화',

  '엑셀':'엑셀/VBA',

  '영어':'커뮤니케이션',
	'스피치':'커뮤니케이션',

  '리더':'리더십',
	'MBA':'리더십',

  '출판':'창업 코스',
	'1인마켓':'창업 코스',
	'1인 쇼핑몰':'창업 코스',
  '창업' : '창업 코스',

  '취업':'취업 코스',
	'취준':'취업 코스',

  '재무':'회계/재무/세무',
  '권오상':'회계/재무/세무',

  '부동산':'부동산 개발',

  '구글 애널리틱스':'데이터분석',
  'ADsP':'데이터분석',
  '데이터사이언스':'데이터분석',
  '데이터 사이언스':'데이터분석',
  '데이터 분석':'데이터분석',
  '데이터분석':'데이터분석',
  'SQL':'데이터분석',

  '데이터 사이언티스트':'데이터엔지니어링',

  '딥러닝':'딥러닝/인공지능',
	'자연어':'딥러닝/인공지능',

  'UX/UI':'UX/UI',

  '드로잉':'디자인툴',

  '일러스트':'일러스트',
	'캐릭터':'일러스트',
	'이모티콘':'일러스트',

  '디자이너':'디자이너 커리어',
  '디자인':'디자이너 커리어',

  '디지털 마케팅' : '디지털마케팅',
  'SNS 마케팅' : 'SNS마케팅',
  '데이터 마케팅' : '데이터마케팅',
  '데이터기반 마케팅' : '데이터마케팅',
  '콘텐츠 마케팅' : '디지털마케팅',
	'콘텐츠 마케터':'디지털마케팅',
  '마케터':'디지털마케팅',
  

  # 포괄 범위가 커서 후순위여야 하는 Sub 조건

  '마케팅' : '마케팅',
  '직장인':'업무자동화',
  '영상':'영상 편집',
  '투자':'금융/투자 실무',
  '앱':'모바일앱',
  '파이썬':'코딩 입문',
  '코딩':'코딩 입문',
  '개발':'개발자 커리어',
}

# rowdata가 10만 단위이기 때문에 연산에서 에러가 발생
# 해당 에러를 무시하고 진행하기 위해 에러 무시 옵션 설정
pd.set_option('mode.chained_assignment',  None)

# Key : Values 매칭
for i in maplist:
  df.subcategory_title[(df['course_title'].str.contains(i)==True)&(df['subcategory_title'].isnull())]=maplist.get(i)

# 결측치 검증
# 모든 Course_title을 기준으로, Subcategory_title에 공백이 있는 값을 추출
df2 = df.loc[(df['course_title'].str.contains('')==True)&(df['subcategory_title'].isnull())]
df2

Empty DataFrame
Columns: [course_title, category_title, subcategory_title]
Index: []

In [ ]:
# 한번 더 검증
print("* 데이터 칼럼별 결측값 확인")
print("----------------------------------------------------------------------")
df.isnull().sum()

* 데이터 칼럼별 결측값 확인
----------------------------------------------------------------------

course_title         0
category_title       7
subcategory_title    0
dtype: int64

In [ ]:
# 팀원 공유를 위한 엑셀 데이터 추출
df.to_excel(r'/content/drive/MyDrive/00.이어드림/Project/FC Data analysis Project\MissingValueShooting.xlsx', index = False)

In [ ]:
## Course_title을 기준으로 한 결측치 처리 완료
## 1차 공유 이후 To do list

# 1. 맵핑 코드 간략화 및 맵핑 순서 설정
#   1-1) 맵핑 코드 간략화
#        맵핑 코드 간략화의 경우, 각 카테고리별로 리스트를 하여 보다 명확하게 알 수 있도록 수정

#   1-2) 맵핑 순서 설정
#        맵핑 순서의 경우, 프론트 엔드 등의 큰 카테고리를 먼저 설정한 뒤, 분류가 애매한 카테고리를 처리하는 순서로 진행
#        ex) (코딩:코딩 입문) 설정이 (풀스텍:웹개발)보다 먼저 설정된다면, 웹개발에 대한 데이터가 코딩 입문으로 들어갈 수 있음
#        ⮕ 작은 카테고리를 먼저할 경우, 데이터가 오염될 가능성이 존재
#        정리) 큰 카테고리 ⮕ 작은 카테고리로 매핑 진행


# 2. 기존의 subcategory_title과 수정한 subcategory_title의 불일치 확인 및 통일 작업
#    ex)기존 subcategory_title에서 SQL은 프로그래밍과 데이터 사이언스로 나눠짐
#       결측치 수정할 때, SQL의 Subcategory를 '데이터분석'으로 설정함


# 3. 기존 'category_title - subcategory_title'의 관계와 수정한 'category_title - subcategory_title'의 관계가 다른 raw들 통일
#   3-1. 최종 완료된 'category_title - subcategory_title' 관계 스키마 시각화