# 오프라인_초급_취업 6조 팀 프로젝트_데이터 분석 - 공통적으로 처리한 데이터 전처리 및 해당으로 인해 추출한 엑셀 처리 코드들

## 조 소개 및 역할 분담
- 조원 : 김지혜, 권민경, 권오균, 송지원, 오세연, 윤상현
- TL : 김지혜
- 보고서 : 오세연
- 발표자 : 윤상현
- 데이터 분석 : 조원 모두
- 데이터 분석에 대한 검토 및 확인 : 권민경

### 인사이트 간략 요약

- WHO : 마케팅(윤상현, 송지원, 오세연) / 손실분석(김지혜, 권오균, 권민경)
- WHEN : 2022-05-09 ~ 2022-05-23 (05-20 자료 제출)
- WHERE : Google Colabotary 환경 기반
- WHAT : Raw data - 파이널프로젝트_RAW_210329_210926.xlsx 기반
- HOW : 저희 팀은 회사의 시점에서 볼 때 가장 크게 고려하는 이익과 손실을 기반으로 인사이트를 진행하기로 하였으며, 이에 팀을 두 팀으로 나누어, 한 팀은 이익을 파악하기 위한 마케팅 팀, 다른 팀은 손실을 파악하기 위한 손실분석 팀으로 나누어 관점을 여러 방면으로 보려고 합니다. 
=> 이익(마케팅)과 손실(손실분석)으로 나누어서 인사이트 동시 진행 / Target 대상 : 개인/취업준비생

    * 마케팅 : 카테고리별 및 구매 단계 혹은 고객의 의사에 대한 데이터를 분석하고, 구매율과 시계열 데이터를 기반으로 이익을 늘릴 수 있는 targeting 대상에게 연관 혹은 관련 강의 상품을 추가적으로 판매할 수 있을만 한 데이터 분석.
    * 손실분석 : Target 대상인 고객이 구매를 취소한 혹은 확정 짓지 않은 내용 등을 구분하여 손실을 분석하고, 환불과 취소 등을 줄일 수 있는 인사이트 획득하여 카테고리 별 혹은 가격이나 할인율에 따른 구매의사결정(type, state) 분석

- WHY : 현실에서도 회사에서 가장 기본적으로 파악하는 것이 손실의 최소화와 이익의 극대화이며, 때로는 이들이 관계를 이루거나 같이 얽혀있기 때문에 회사의 입장에서 보는 실전이라고 가정하였기에 동시 진행하려 합니다. 또한, 개인을 대상으로 하는 사유는 기업 및 B2C, B2G 등 개인이 아닌 단체와의 거래는 특수성 및 변동사항이 많기 때문에 분석이 용이한 개인을 위주로 진행하였습니다.

# 1. 주제 선정에 대하여

##배경 및 1차 주제
- 팀 프로젝트 과제로서, 실전에 대비하여 전달받은 패스트캠프(이하 FC)의 구매내역 raw data를 기반으로 해당 팀에서 원하는 주제 및 방향 등을 자유롭게 정하여 데이터 분석, EDA 를 개인이 아닌 팀 단위로 진행하는 것으로, 저희 취업 초급 오프라인 6조(이하 6조)는 정말로 해당의 회사에서 데이터에 대한 분석을 진행한다면, 회사라는 관점에서 필요한 내용에 대해 고려했고, 그에 대해 이익과 손실이라는 큰 대주제를 가지고 진행하기로 하셨습니다. 

    또한, 이익을 창출하게 만드는 주 고객 대상, 즉 Target 이 될 대상을 단체나 회사가 아닌 개인을 주 타게팅 대상으로 보았으며, 이들을 목표로 하여 방향을 잡고 진행하였습니다.

##사유
- 회사라는 단체는 기본적으로 이익을 추구하되, 이익을 추구하는 방향은 크게 두 가지로 나뉩니다. 이익을 극대화 하거나, 손실을 최소화 하거나. 그렇기에 저희는 이익을 극대화 하는 방향인 이익을 추가로 늘릴 수 있는 마케팅 팀과, 손실을 최소화하는 방향으로 손실에 대한 분석을 진행하는 손실분석 팀으로 나누었습니다. 

    또한, 주 타게팅 대상을 개인에 한정한 사유는, 회사나 단체의 경우 특정한 조건이 주어지지 않는 한은 구매를 하는 경우가 적기 때문이며 대다수가 특이사항이 많아 통일된 내용이 없기에 제외하였고, 개인은 해당 인사이트 및 결론 도출 방향에 따라서 주 고객층이 다시금 FC의 강의를 재구매 할 수 있는 가능성을 볼 수 있기 때문입니다.

## 최종 주제
해당 데이터에 기반하여 마케팅(송지원, 오세연, 윤상현)과 손실분석(김지혜, 권민경, 권오균)으로 팀을 나누어 이익에 대한 방향과 손실에 대한 방향으로 각자 분석한 뒤에 취합하여 회사에 이익이 되는 결론을 도출하는 것입니다.

# 데이터 분석 전 기본적인 환경 setting

## 기본적인 공통 setting

In [ ]:
# 한글깨짐 방지 - 해당 가장 먼저 실행 후 Restart and run all 
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree
Reading state information... Done
fonts-nanum is already the newest version (20170925-1).
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 42 not upgraded.
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 10 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [ ]:
# google drive mount
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# 필요모듈 import

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# For google colab memory issue
pd.set_option('mode.chained_assignment',  None)

In [ ]:
# 폰트 나눔바른고딕 지정
plt.rc('font', family='NanumBarunGothic')

In [ ]:
# 데이터 프레임 화
path = '/content/drive/MyDrive/offline6_FC_EDA/'
df = pd.read_excel(path+'파이널프로젝트_RAW_210329_210926.xlsx')
# 경로는 개인의 환경에 맞게 수정 처리

## 기본적인 데이터 확인 - 데이터 프레임 확인, 정보, 간략한 평균치, 기본 df의 결측치 여부 등

#### 간단 데이터 조회 - 상위 5개 확인으로 columns 확인

In [ ]:
df.head()

,id,customer_id,course_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,tax_free_amount,pg,method,subcategory_title,marketing_start_at
0,970634,504760.0,201435.0,ORDER,CANCELLED,올인원 패키지 : 알고리즘 기술면접 완전 정복,프로그래밍,올인원,2021-03-28 15:00:11,90500,NaN,NaN,110500.0,110500.0,NaN,VBANK,개발자 커리어,NaT
1,970650,432862.0,203178.0,ORDER,CANCELLED,초격차 패키지 : 한번에 끝내는 영상 촬영과 편집,영상/3D,올인원,2021-03-28 15:16:53,96000,NaN,NaN,116000.0,116000.0,NaN,CARD,영상 편집,2020-12-02
2,970657,72297.0,204246.0,PAYMENT,COMPLETED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,[10% 할인] 시크릿코드 실무 완성편,19090.0,190900.0,190900.0,NaN,CARD,NaN,2021-03-04
3,970656,72297.0,204246.0,ORDER,CANCELLED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,NaN,NaN,190900.0,190900.0,NaN,CARD,NaN,2021-03-04
4,970658,478028.0,201797.0,PAYMENT,COMPLETED,올인원 패키지 : 직장인 필수 스킬 3종 세트 MAX,업무 생산성,올인원,2021-03-28 15:21:54,97500,[웰컴쿠폰] 올인원 패키지 2만원 할인 쿠폰,20000.0,117500.0,117500.0,NaN,CARD,PPT/보고서,2019-11-14

## Column 정보

- 패스트캠퍼스로부터 전달받은 내용을 기반으로 인사이트에 맞는 방향성을 위해 조절해야 할 column 등에 대한 정리 및 자세한 내용


#### column이름 (데이터타입) : 상세 설명 및 추정 내용

1. **id (int)** : 현 상태 status, 매 단계에 대한 id 정보로서, 결제 및 고객의 해당 강의 에 대한 행위의 변경에 따른 시점아니 상태에 변화에 따라서 각 id 부여됨. Unique. PK

2. **customer_id (int)** : 고객 id로서, 중복치 있음 -> 한 고객이 하는 행위에 따라 여러 상태가 생기기 때문.

3. **course_id (int)** : 강의별 id이기는 하나, 해당의 id가 부여되는 경우는 order인 수강신청에서 결제payment 단으로 넘어가면 생성됨(payment가 pending 이어도 course_id 생성된 것 확인함 - ex. 204265)

4. **type (string)** :
ORDER - 수강신청 완료한 상태 = 사용자가 강의를 듣겠다고 결정함 
PAYMENT - 결제 단계로 넘어감. 
TRANSACTION - 3개 뿐인 것으로 확인되며, 거진 삭제된 강의로 확인되어 drop 확정.
REFUND - 환불처리.

5. **state (string)** : 
COMPLETED - 완료된 상태. 
REQUESTED - 고객에게 결제를 요청한 단계로 PAYMENT 단계에만 있음.
PENDING - 고객이 결제 진행 중인 단계. 역시 PAYMENT 단계에만 있으며, 위 둘은 가설의 방향에 강화를 할 때에만 사용하는 것이 좋아보임.
CANCELLED - 상태의 대한 CANCELLED로서 ORDER에 대한 CANCELLED는 아래 i) 참조. PAYMRNT에 대한 CANCELLED는 말 그대로 결제 완료가 아닌 결제 중 취소한 것.

HIDDEN - 엑셀에 내용 없음. 무시.
DELETE - drop. 이미 삭제된 내용이며 수가 적으므로 유의미해 보이지 않아서 drop 처리 확정.

+ 다만 type의 ORDER가 실질적으로는 ORDER-COMPLETED 여야 하는데 ORDER-CANCELLED 인 경우가 있음(ORDER-COMPLETE 이후 바로 PAYMENT 단계로 넘어간 경우) 아래 i) 참조.
    i) 이런 케이스는 customer_id 로 group으로 묶어서 조회 후, completed_at 시간을 봐서 ORDER-CANCELLED 이후 PAYMENT 단계로 넘어간 경우 ORDER-CANCELLED 를 ORDER-COMPLETED 로 처리하기로 결정(10-05-22)


6. **course_title (string)** : 강의명. 

7. **category_title (string)** : 대분류. 카테고리별.
띄어쓰기로 인한 같은 내용임에도 데이터가 따로 분류가 되는 것이 있으며, 통일할 수 있는 내역은 통일하기로 결정 이하 내용으로 진행.

    - 데이터 사이언스 -> 데이터사이언스 로 통일
    - 파이낸스 & 비지니스 -> 비지니스로 통일
    - 띄어쓰기는 다 붙여버리기
    - 서브 카테고리를 정리해서 카테고리에 넣기

8. **format (string)** : 강의를 나누는 기준 -> 강의 기획 당시의 형태 결정 여부. 컨셉 차이.

9. **completed_at (date)** : 고객의 결제완료 시점. 거래 내역 데이터.

10. **transaction_amount (int)** : 최종 결제 금액. -> 네이버페이 및 다른 결제과정 상의 포인트나 쿠폰은 제외한 패스트캠퍼스에서 고객에게 받는 실질 금액. => '실질 결제된 금액(pg및 기타 포인트 등 할인 제외된 금액)'

11. **coupon_title (string)** : 쿠폰명. 발행된 쿠폰들은 각자의 쿠폰의 효과가 적용된 다른 entity. 여러 강의에 적용될 수 있다. 하지만 실제 coupon_id는 다를 수 있음 확인. 하나의 조건으로서 고려.

12. **coupon_discount_amount (int)** : 할인 금액.

13. **sale_price (int)** : ‘판매 공시가’ 

14. **tax_free_amount (int)** : 원래는 VAT를 제외한 금액이어야 하는데, 주어진 데이터에서는 다 같은 것으로 확인.

15. **pg (string)** : PG(Payment Gateway)라고 해서 실제로 온라인 거래할 때 사용하는 금융거래 대행사를 의미. (e.g. 카카오페이, 토스페이먼트, U+ pay 등..) 비어있는 것은 default PG사를 의미. (LG U+ 같은 언급이 안되어있는 다른 회사중에 하나) 확인함.

16. **method (string)** : 결제방법. VBANK = 가상계좌를 통한 결제방법. 일반적인 다른 온라인 결제에서 통용되는 것과 같음.

17. **subcategory_title (string)** : category_title의 하위 분류 확인. 중(소)분류

18. **marketing_start_at (date)** : 해당 강의의 마케팅이 시작된 기준. 여기서 마케팅 날짜는 해당 강의를 판매한 시점으로 고려. (즉, landing page가 최초로 올라간 시점) = 강의가 판매되기 시작한 시점.

기타1 : 기업/개인 단을 따로 분류한 가상컬럼을 실제 컬럼으로 추가하는 여부 확인 요망

기타2 : 고객 주 타켓 기준을 개인_취업 준비생으로 잡았으므로, B2B등 개인 위주가 아닌 내용은 drop.

#### 결측치 확인 및 데이터 타입 확인

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105419 entries, 0 to 105418
Data columns (total 18 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      105419 non-null  int64
 1   customer_id             105416 non-null  float64
 2   course_id               100212 non-null  float64
 3   type                    105419 non-null  object
 4   state                   105419 non-null  object
 5   course_title            105403 non-null  object
 6   category_title          105395 non-null  object
 7   format                  105403 non-null  object
 8   completed_at            105419 non-null  datetime64[ns]
 9   transaction_amount      105419 non-null  int64
 10  coupon_title            31817 non-null   object
 11  coupon_discount_amount  31817 non-null   float64
 12  sale_price              104291 non-null  float64
 13  tax_free_amount         104291 non-null  float64
 14  pg                      90344 non-null   object
 15  method                  92323 non-null   object
 16  subcategory_title       85590 non-null   object
 17  marketing_start_at      87440 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(5), int64(2), object(9)
memory usage: 14.5+ MB

#### 각 column 별 결측 데이터 갯수 확인하기

In [ ]:
# 각 column 별 결측값 갯수
df.isnull().sum()

id                            0
customer_id                   3
course_id                  5207
type                          0
state                         0
course_title                 16
category_title               24
format                       16
completed_at                  0
transaction_amount            0
coupon_title              73602
coupon_discount_amount    73602
sale_price                 1128
tax_free_amount            1128
pg                        15075
method                    13096
subcategory_title         19829
marketing_start_at        17979
dtype: int64

#### 데이터의 각 필드 데이터 분포(평균, 최소값, 최대값 등)를 살펴보기

In [ ]:
df.describe()

,id,customer_id,course_id,transaction_amount,coupon_discount_amount,sale_price,tax_free_amount
count,1.054190e+05,105416.000000,100212.000000,1.054190e+05,3.181700e+04,1.042910e+05,1.042910e+05
mean,1.147054e+06,417248.252742,203868.586327,1.464814e+05,4.972172e+04,1.610808e+05,1.575551e+05
std,1.125898e+05,206414.496648,1534.583331,7.195061e+05,5.624467e+04,3.955298e+05,3.898133e+05
min,5.679930e+05,16.000000,2516.000000,-4.144074e+06,0.000000e+00,1.000000e+00,0.000000e+00
25%,1.048940e+06,256401.000000,203100.000000,8.350000e+04,2.000000e+04,1.090000e+05,1.090000e+05
50%,1.135186e+06,501046.000000,203787.000000,1.175000e+05,2.100000e+04,1.320000e+05,1.320000e+05
75%,1.240472e+06,566595.000000,204775.000000,1.590000e+05,6.915000e+04,1.710000e+05,1.710000e+05
max,1.381657e+06,672308.000000,207742.000000,1.134000e+08,2.000000e+06,9.094000e+07,9.094000e+07

In [ ]:
# 기본적인 데이터의 갯수 : 105419 / column 갯수 : 18 확인
# 결측 없는 id, type, state, completed_at, transaction_amount 확인

## 팀 공통의 데이터 처리

### 1차 결측치 및 drop 할 데이터 처리 (subcategory_title, coupon 제외)_권오균, 권민경

In [ ]:
# tax_free_amount drop : 효용성 없음으로 인해 drop
df.drop(['tax_free_amount'], axis=1, inplace=True)

In [ ]:
# TRANSACTION drop : 너무 적은 수의 data 라서 drop
df.drop(df[df['type']=='TRANSACTION'].index, inplace=True)

In [ ]:
# DELETED drop : 삭제되어 의미 없는 data 로 판단되어 drop
df.drop(df[df['state']=='DELETED'].index, inplace=True)

In [ ]:
# format 결측치 drop
df.drop(df[df['format'].isna()==True].index, inplace=True)

In [ ]:
# course_title 결측치 drop
df.drop(df[df['course_title'].isna()==True].index, inplace=True)

In [ ]:
# category_title 결측치 drop
df.drop(df[df['category_title'].isna()==True].index, inplace=True)

In [ ]:
# category_title='관리' drop : 너무 적은 수이며, 타겟 고객층의 정보와도 맞지 않아 drop
df.drop(df[df['category_title'] == '관리'].index, inplace=True)

In [ ]:
# category_title 공백 제거 : 중복 방지
df['category_title'] = df['category_title'].str.replace(" ", "")

In [ ]:
# category_title= 파이낸스 -> 비즈니스 변환 : 하나로 통합.
df['category_title'] = df['category_title'].str.replace("파이낸스","비즈니스")

In [ ]:
# category_title= 일러스트, 일러스트 -> 디자인 & subcategory_title= 일러스트 : 역시 하나로 통합
df.loc[df[df['category_title'] == '일러스트']['subcategory_title'].index, 'subcategory_title'] = '일러스트'
df['category_title'] = df['category_title'].str.replace("일러스트","디자인")

In [ ]:
# sale_price = 1 drop : 제대로 된 판매가가 아닌 특수상황의 경우들이므로 drop
df.drop(df[df['sale_price'] == 1].index, inplace=True)

In [ ]:
# sale_price 결측치, transaction_amount 절대값으로 fillna
df['sale_price'] = df['sale_price'].fillna(df['transaction_amount'].abs())

In [ ]:
# sale_price 이상치 처리(sale_price 75%(IQR3) * 3 이상 drop)
# sale_price 이상치 중에 작은 값제거 X (min fence)
# sale_price 중에서 이상치가 하단부의 이상치는 사용할 것이고, 상단부는 사용하지 않기 때문에,
def remove_out(dataframe, remove_col):
    dff = dataframe
    for k in remove_col:
        level_1q = dff[k].quantile(0.25)
        level_3q = dff[k].quantile(0.75)
        IQR = level_3q - level_1q
        rev_range = 3  # 제거 범위 조절 변수
        dff = dff[dff[k] <= level_3q + (rev_range * IQR)] # 해당의 코드로 상단부 이상치만 drop하고 나머지만 활용하기 위하여 처리
        dff = dff.reset_index(drop=True)
    return dff
df = remove_out(df, ['sale_price'])

### 금액 관련 내용에 대한 처리_김지혜

In [ ]:
# error, warning 무시 --> 경고 무시하고 실행
pd.set_option('mode.chained_assignment',  None)

In [ ]:
# coupon_discount_amount 결측치 , sale_price - transaction_amount 값으로 fillna 
df['coupon_discount_amount'] = df['coupon_discount_amount'].fillna(df['sale_price']- df['transaction_amount'])

In [ ]:
# coupon_discount_amount 잘못된 값 변경
df.coupon_discount_amount[df['transaction_amount'] <0] = df['sale_price'] + df['transaction_amount']

In [ ]:
# 해당 조건 만족하는 coupon_title에 REFUND 입력
df.coupon_title[(df['type'].str.contains('REFUND')==True)&(df['coupon_title'].isna())] = 'REFUND'

In [ ]:
# 해당 조건 만족하는 coupon_title에 coupon_unapplied 입력
df.coupon_title[(df['coupon_title'].isna()) & (df['coupon_discount_amount'] == 0)] = 'coupon_unapplied'

In [ ]:
# 해당 조건 만족하는 coupon_title에 coupon_applied 입력
df.coupon_title[(df['coupon_title'].isna()) & (df['coupon_discount_amount'] > 0) & (df['transaction_amount'] > 0)] = 'coupon_applied'

In [ ]:
# coupon_discount_amount < 0 drop 
# coupon_discount_amount = (sale - transaction)
df.drop(df[df['coupon_discount_amount'] < 0].index, inplace = True)

### 카테고리 관련 데이터 공통 처리 내역_윤상현, 송지원

In [ ]:
# 의미가 없는 Course_title raw들 삭제를 위한 리스트 작성 테스트

# 개인에 대한 마케팅이 목표이기 때문에 B2B Raw Drop
# 그 이외에 FC에서 Test를 위해 사용한 데이터와
# 1개의 예외로 판단되는 자유이용권 raw drop

droplist = ['B2B','TEST','test','자유이용권']
dropjoin = '|'.join(droplist)

# Course_title에 droplist안에 있는 글자가 있는 raw가 있다면 해당 raw를 드랍
droplist = ['B2B','TEST','test','자유이용권']
dropjoin = '|'.join(droplist)

df = df[df["course_title"].str.contains(dropjoin) == False]

In [ ]:
## 딕셔너리를 사용하여 Course_title에 Key로 들어간 글자가 있고,
## Subcategory_title가 null값이라면,
## Subcategory_title에 Values값을 반환

# 맵핑 리스트 {Key : Values}
maplist= {
  '리팩터링':'개발자 커리어',
	'Top tier 프로젝트':'개발자 커리어',
	'주니어':'개발자 커리어',
  
  '프론트':'프론트엔드 개발',
  'React':'프론트엔드 개발',

  'DevOps':'DevOps',

  'iOS':'모바일앱',
	'AOS':'모바일앱',	

  'JPA':'백엔드 개발',
	'Spring':'백엔드 개발',
	'스프링':'백엔드 개발',
	'Java':'백엔드 개발',
	'Node':'백엔드 개발',

  '프로그래밍 입문':'코딩 입문',
	'프로그래밍 유치원':'코딩 입문',
	'클론':'코딩 입문',
	'알고리즘':'코딩 입문',
	'따라잡기' : '코딩 입문',

  '풀스텍':'웹개발',
	'풀스택':'웹개발',
	'웹 개발': '웹개발',
  
  '유튜브':'영상 편집',
	'유튜버':'영상 편집',

  'VFX' : 'VFX',

  '모션그래픽':'모션그래픽',
	'Render':'모션그래픽',
	'Financial':'금융/투자 실무',

  'PPT':'PPT/보고서',
	'기획서':'PPT/보고서',

  '업무자동화':'업무자동화',
	'직무 스킬':'업무자동화',

  '엑셀':'엑셀/VBA',

  '영어':'커뮤니케이션',
	'스피치':'커뮤니케이션',

  '리더':'리더십',
	'MBA':'리더십',

  '출판':'창업 코스',
	'1인마켓':'창업 코스',
	'1인 쇼핑몰':'창업 코스',
  '창업' : '창업 코스',

  '취업':'취업 코스',
	'취준':'취업 코스',

  '재무':'회계/재무/세무',
  '권오상':'회계/재무/세무',

  '부동산':'부동산 개발',

  '구글 애널리틱스':'데이터분석',
  'ADsP':'데이터분석',
  '데이터사이언스':'데이터분석',
  '데이터 사이언스':'데이터분석',
  '데이터 분석':'데이터분석',
  '데이터분석':'데이터분석',
  'SQL':'데이터분석',

  '데이터 사이언티스트':'데이터엔지니어링',

  '딥러닝':'딥러닝/인공지능',
	'자연어':'딥러닝/인공지능',

  'UX/UI':'UX/UI',

  '드로잉':'디자인툴',

  '일러스트':'일러스트',
	'캐릭터':'일러스트',
	'이모티콘':'일러스트',

  '디자이너':'디자이너 커리어',
  '디자인':'디자이너 커리어',

  '디지털 마케팅' : '디지털마케팅',
  'SNS 마케팅' : 'SNS마케팅',
  '데이터 마케팅' : '데이터마케팅',
  '데이터기반 마케팅' : '데이터마케팅',
  '콘텐츠 마케팅' : '디지털마케팅',
	'콘텐츠 마케터':'디지털마케팅',
  '마케터':'디지털마케팅',
  

  # 포괄 범위가 커서 후순위여야 하는 Sub 조건

  '마케팅' : '마케팅',
  '직장인':'업무자동화',
  '영상':'영상 편집',
  '투자':'금융/투자 실무',
  '앱':'모바일앱',
  '파이썬':'코딩 입문',
  '코딩':'코딩 입문',
  '개발':'개발자 커리어',
}

# rowdata가 10만 단위이기 때문에 연산에서 에러가 발생
# 해당 에러를 무시하고 진행하기 위해 에러 무시 옵션 설정
pd.set_option('mode.chained_assignment',  None)

# Key : Values 매칭
for i in maplist:
  df.subcategory_title[(df['course_title'].str.contains(i)==True)&(df['subcategory_title'].isnull())]=maplist.get(i)

In [ ]:
## Format이 B2G인 row Drop
df.drop(df[(df['format'].str.contains('B2G')==True)].index, inplace=True)

In [ ]:
df[(df['format'].str.contains('B2G')==True)]

Empty DataFrame
Columns: [id, customer_id, course_id, type, state, course_title, category_title, format, completed_at, transaction_amount, coupon_title, coupon_discount_amount, sale_price, pg, method, subcategory_title, marketing_start_at]
Index: []

### type 과 state 에 대한 정리_오세연
- ORDER 의 COMPLETED 여야 함에도, 이전의 데이터의 처리 과정에 따라 21년 7월 이전의 ORDER의 내역 중 ORDER COMPLETED 가 아니라, ORDER CANCELLED 처리가 된 데이터들이 있어, 해당의 기준을 ORDER_COMPLETED 와 PAYMENT_COMPLETED 가 같은 강의로 한 사람의 사용자가 같은 시간대에 이용한 것을 기반으로 하여, 조건식에 따라 ORDER의 state 상태를 정리
- 사유 : ORDER 라는 상태 자체가 고객이 구매에 대한 고민을 하거나 구매에 대한 결정을 했다는 상태를 보여주기 때문.

In [ ]:
# copy the df just in case & not to corrupt data
test = df.copy()
test # 99068 rows × 17 columns

,id,customer_id,course_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,pg,method,subcategory_title,marketing_start_at
0,970634,504760.0,201435.0,ORDER,CANCELLED,올인원 패키지 : 알고리즘 기술면접 완전 정복,프로그래밍,올인원,2021-03-28 15:00:11,90500,coupon_applied,20000.0,110500.0,NaN,VBANK,개발자 커리어,NaT
1,970650,432862.0,203178.0,ORDER,CANCELLED,초격차 패키지 : 한번에 끝내는 영상 촬영과 편집,영상/3D,올인원,2021-03-28 15:16:53,96000,coupon_applied,20000.0,116000.0,NaN,CARD,영상 편집,2020-12-02
2,970657,72297.0,204246.0,PAYMENT,COMPLETED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,[10% 할인] 시크릿코드 실무 완성편,19090.0,190900.0,NaN,CARD,프론트엔드 개발,2021-03-04
3,970656,72297.0,204246.0,ORDER,CANCELLED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,coupon_applied,19090.0,190900.0,NaN,CARD,프론트엔드 개발,2021-03-04
4,970658,478028.0,201797.0,PAYMENT,COMPLETED,올인원 패키지 : 직장인 필수 스킬 3종 세트 MAX,업무생산성,올인원,2021-03-28 15:21:54,97500,[웰컴쿠폰] 올인원 패키지 2만원 할인 쿠폰,20000.0,117500.0,NaN,CARD,PPT/보고서,2019-11-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99063,1364995,640697.0,205365.0,PAYMENT,CANCELLED,초격차 패키지 : 한 번에 끝내는 유튜브 크리에이터 되기,영상/3D,올인원,2021-09-25 14:10:42,96000,[WELCOME] 온라인 강의 2만원 할인쿠폰,20000.0,116000.0,INICIS,TRANS,영상 편집,2021-06-15
99064,1364998,670896.0,204159.0,PAYMENT,CANCELLED,부동산 디벨로퍼 아카데미 : 인허가,부동산/금융,올인원,2021-09-25 14:16:33,189000,coupon_unapplied,0.0,189000.0,INICIS,CARD,부동산 개발,2021-02-10
99065,1364996,640697.0,205365.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 유튜브 크리에이터 되기,영상/3D,올인원,2021-09-25 14:17:41,96000,[WELCOME] 온라인 강의 2만원 할인쿠폰,20000.0,116000.0,INICIS,VBANK,영상 편집,2021-06-15
99066,1365005,670896.0,204159.0,PAYMENT,CANCELLED,부동산 디벨로퍼 아카데미 : 인허가,부동산/금융,올인원,2021-09-25 14:19:56,189000,coupon_unapplied,0.0,189000.0,INICIS,CARD,부동산 개발,2021-02-10
99067,1365007,610626.0,206720.0,PAYMENT,COMPLETED,용호수의 돈 버는 실전 영상 제작,영상/3D,올인원,2021-09-25 14:25:47,139000,[WELCOME] 온라인 강의 3만원 할인쿠폰,30000.0,169000.0,NAVER,POINT,영상 편집,2021-08-17

In [ ]:
# conditions for intersecting datasets -> 조건(ORDER_CANCELLED 와 PAYMENT_COMPLETED)
odrcan = test[(test['type'] == 'ORDER') & (test['state'] == 'CANCELLED')] # 34121 rows × 17 columns
paycom = test[(test['type'] == 'PAYMENT') & (test['state'] == 'COMPLETED')] # 51706 rows × 17 columns

In [ ]:
# order_cancelled 이면서, payment_completed인 사람들 바꿔야 할 대상.
inter = odrcan[odrcan['customer_id'].isin(paycom['customer_id']) == True]
inter # 21996 rows × 17 columns

,id,customer_id,course_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,pg,method,subcategory_title,marketing_start_at
3,970656,72297.0,204246.0,ORDER,CANCELLED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,coupon_applied,19090.0,190900.0,NaN,CARD,프론트엔드 개발,2021-03-04
5,970655,478028.0,201797.0,ORDER,CANCELLED,올인원 패키지 : 직장인 필수 스킬 3종 세트 MAX,업무생산성,올인원,2021-03-28 15:21:56,97500,coupon_applied,20000.0,117500.0,NaN,CARD,PPT/보고서,2019-11-14
9,970667,478033.0,203178.0,ORDER,CANCELLED,초격차 패키지 : 한번에 끝내는 영상 촬영과 편집,영상/3D,올인원,2021-03-28 15:26:48,96000,coupon_applied,20000.0,116000.0,NaN,CARD,영상 편집,2020-12-02
11,970668,469860.0,203644.0,ORDER,CANCELLED,올인원 패키지 : 권오상의 금융 아카데미 - 권오상의 재무제표 분석 기초(평생소장),부동산/금융,올인원,2021-03-28 15:27:17,263000,coupon_unapplied,0.0,263000.0,NaN,CARD,회계/재무/세무,2020-11-27
12,970670,429291.0,NaN,ORDER,CANCELLED,프로모션 : 코딩 LEVEL UP 웹 개발 풀스텍 한끝세트 (3월 프리패스),프로그래밍,올인원,2021-03-28 15:27:29,299000,coupon_unapplied,0.0,299000.0,NaN,CARD,웹개발,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72002,1231936,601989.0,204013.0,ORDER,CANCELLED,올인원 패키지 : 완전정복 시각디자인 기초,디자인,올인원,2021-07-21 13:22:58,143000,coupon_applied,30000.0,173000.0,KAKAO,NaN,시각디자인,2021-03-16
72009,1231980,99019.0,200681.0,ORDER,CANCELLED,올인원 패키지 : 머신러닝과 데이터분석 A-Z,데이터사이언스,올인원,2021-07-21 13:46:31,147500,coupon_unapplied,0.0,147500.0,INICIS,CARD,머신러닝,2019-05-17
72016,1231991,542379.0,205879.0,ORDER,CANCELLED,올인원 패키지 : 누적 다운로드 120만+ 1인 개발자와 함께하는 앱 개발 입문,프로그래밍,올인원,2021-07-21 13:49:02,139000,coupon_unapplied,0.0,139000.0,INICIS,VBANK,모바일앱,2021-07-02
72025,1232009,542379.0,205879.0,ORDER,CANCELLED,올인원 패키지 : 누적 다운로드 120만+ 1인 개발자와 함께하는 앱 개발 입문,프로그래밍,올인원,2021-07-21 13:57:23,139000,coupon_unapplied,0.0,139000.0,INICIS,CARD,모바일앱,2021-07-02
72030,1232039,602055.0,205080.0,ORDER,CANCELLED,나의 칼퇴치트키 엑셀유치원,업무생산성,올인원,2021-07-21 14:02:10,119000,coupon_unapplied,0.0,119000.0,NAVER,NaN,엑셀/VBA,NaT

In [ ]:
# 위의 조건에 맞는 대상들의 id 를 기반으로, ORDER의 state 조정
# change wrong order_cancelled to order_completed
for t, testId in test.id.iteritems():
    for i, interId in inter.id.iteritems():
        if testId == interId : 
            if test['type'][t] == 'ORDER' : 
                # test['type'][t] = 'ORDER'
                test['state'][t] = 'COMPLETED'
print('done')

done

In [ ]:
test # 99068 rows × 17 columns # 처음의 복사하기 이전의 df 와 같은 size 확인
df = test # 해당 cmd로 내용 확인 후 덮어쓰기

In [ ]:
df.sort_values(by='id') # 99068 rows × 17 columns

,id,customer_id,course_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,pg,method,subcategory_title,marketing_start_at
55283,567993,157822.0,203166.0,ORDER,CANCELLED,엑셀 온라인 완주반 3기,업무생산성,온라인 완주반,2021-06-24 22:44:11,314000,coupon_unapplied,0.0,314000.0,NaN,CARD,엑셀/VBA,2020-08-14 00:00:00
36064,602828,169872.0,NaN,ORDER,COMPLETED,프로모션 : 데이터 분석 A to Z 평생 PASS (10월),데이터사이언스,올인원,2021-05-23 06:37:16,299000,coupon_unapplied,0.0,299000.0,NaN,CARD,데이터분석,NaT
11966,641594,271174.0,203479.0,ORDER,CANCELLED,승인받는 이모티콘 만들기 온라인 완주반 1기,크리에이티브,온라인 완주반,2021-04-13 16:16:55,352000,coupon_unapplied,0.0,352000.0,NaN,VBANK,일러스트,2020-10-29 00:00:00
38548,675800,286811.0,203644.0,ORDER,CANCELLED,올인원 패키지 : 권오상의 금융 아카데미 - 권오상의 재무제표 분석 기초(평생소장),부동산/금융,올인원,2021-05-27 14:05:34,255000,coupon_unapplied,0.0,255000.0,NaN,CARD,회계/재무/세무,2020-11-27 00:00:00
23858,793663,87425.0,201797.0,ORDER,CANCELLED,올인원 패키지 : 직장인 필수 스킬 3종 세트 MAX,업무생산성,올인원,2021-05-01 15:06:47,103500,coupon_applied,10000.0,113500.0,NaN,CARD,PPT/보고서,2019-11-14 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99065,1364996,640697.0,205365.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 유튜브 크리에이터 되기,영상/3D,올인원,2021-09-25 14:17:41,96000,[WELCOME] 온라인 강의 2만원 할인쿠폰,20000.0,116000.0,INICIS,VBANK,영상 편집,2021-06-15 00:00:00
99064,1364998,670896.0,204159.0,PAYMENT,CANCELLED,부동산 디벨로퍼 아카데미 : 인허가,부동산/금융,올인원,2021-09-25 14:16:33,189000,coupon_unapplied,0.0,189000.0,INICIS,CARD,부동산 개발,2021-02-10 00:00:00
99066,1365005,670896.0,204159.0,PAYMENT,CANCELLED,부동산 디벨로퍼 아카데미 : 인허가,부동산/금융,올인원,2021-09-25 14:19:56,189000,coupon_unapplied,0.0,189000.0,INICIS,CARD,부동산 개발,2021-02-10 00:00:00
99067,1365007,610626.0,206720.0,PAYMENT,COMPLETED,용호수의 돈 버는 실전 영상 제작,영상/3D,올인원,2021-09-25 14:25:47,139000,[WELCOME] 온라인 강의 3만원 할인쿠폰,30000.0,169000.0,NAVER,POINT,영상 편집,2021-08-17 00:00:00
63322,1381657,259102.0,204670.0,PAYMENT,COMPLETED,The RED : 김영하 작가의 내 안의 숨은 이야기를 찾아 쓰는 법,마케팅,RED,2021-07-04 01:07:34,149000,coupon_unapplied,0.0,149000.0,NaN,TRANSFER,글쓰기/카피라이팅,2021-06-18 17:00:00

In [ ]:
# 이하 내용부터는 처리 이후의 내용 확인하기

In [ ]:
# After checking the result
result = test[((test['type'] == 'ORDER') & (test['state'] == 'CANCELLED')) | ((test['type'] == 'PAYMENT') & (test['state'] == 'COMPLETED'))]
result.sort_values(['customer_id','type','state']) # 63831 rows × 17 columns
# rows are changed

,id,customer_id,course_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,pg,method,subcategory_title,marketing_start_at
20013,1036206,16.0,203527.0,ORDER,CANCELLED,올인원 패키지 : 김민태의 프론트엔드 아카데미 : 제 1강 JavaScript & ...,프로그래밍,올인원,2021-04-28 15:55:26,99000,coupon_unapplied,0.0,99000.0,KAKAO,NaN,프론트엔드 개발,2021-04-07
21128,1039780,47.0,203078.0,PAYMENT,COMPLETED,올인원 패키지 : 딥러닝을 활용한 추천시스템 구현,데이터사이언스,올인원,2021-04-29 18:32:15,139500,coupon_unapplied,0.0,139500.0,KAKAO,POINT,딥러닝/인공지능,2020-10-13
66064,1206695,47.0,203533.0,PAYMENT,COMPLETED,연습문제 패키지 : 퀴즈처럼 풀면서 배우는 파이썬 머신러닝 300제+,데이터사이언스,올인원,2021-07-09 16:14:40,104000,coupon_unapplied,0.0,104000.0,KAKAO,POINT,머신러닝,2021-01-05
2237,976946,79.0,200328.0,PAYMENT,COMPLETED,올인원 패키지 : 파이썬 웹 개발,프로그래밍,올인원,2021-03-30 13:59:52,0,수강생 50만명 돌파 기념 감사제 쿠폰,170000.0,124000.0,NaN,PROMOTION,웹개발,NaT
98031,1357458,96.0,207031.0,PAYMENT,COMPLETED,편집하는여자의 영상편집 마스터클래스 - 제 2강 10가지 편집기법으로 프리미어 레벨...,영상/3D,올인원,2021-09-21 17:51:18,289000,coupon_unapplied,0.0,289000.0,INICIS,CARD,영상 편집,2021-09-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99035,1364787,670748.0,204342.0,PAYMENT,COMPLETED,"올인원 패키지 : GA4 탑재, 구글 애널리틱스 끝장내기",마케팅,올인원,2021-09-25 09:11:28,154000,[미래투자금] 온라인 강의 5천원 할인쿠폰,5000.0,159000.0,INICIS,VBANK,데이터마케팅,2021-04-02
99050,1364883,670787.0,205687.0,PAYMENT,COMPLETED,올인원 패키지 : 노잼봇과 함께 배우는 파이썬 유치원,프로그래밍,올인원,2021-09-25 11:49:51,139000,[미래투자금] 온라인 강의 1만원 할인쿠폰,10000.0,149000.0,INICIS,CARD,코딩 입문,2021-08-30
99048,1364875,670817.0,203942.0,PAYMENT,COMPLETED,초격차 패키지 : 30개 프로젝트로 배우는 Android 앱 개발 with Kotlin,프로그래밍,올인원,2021-09-25 11:29:36,172000,coupon_unapplied,0.0,172000.0,KAKAO,POINT,모바일앱,2021-02-25
99055,1364919,670833.0,201582.0,PAYMENT,COMPLETED,올인원 패키지 : 컴퓨터 공학 전공 필수,프로그래밍,올인원,2021-09-25 12:08:05,169000,[미래투자금] 온라인 강의 2만원 할인쿠폰,20000.0,189000.0,INICIS,CARD,개발자 커리어,2019-09-30
99062,1364991,670891.0,203935.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 파이썬 웹 개발,프로그래밍,올인원,2021-09-25 14:01:26,159000,[미래투자금] 온라인 강의 2만원 할인쿠폰,20000.0,179000.0,INICIS,CARD,백엔드 개발,2021-05-31

In [ ]:
# testing the result to compare with original df(df) and resulted df(test)
test[test['customer_id'] == 172.0]

,id,customer_id,course_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,pg,method,subcategory_title,marketing_start_at
10608,1004041,172.0,203530.0,ORDER,COMPLETED,초격차 패키지 : 한 번에 끝내는 반복 업무 자동화,업무생산성,올인원,2021-04-11 14:45:51,90000,coupon_applied,10000.0,100000.0,INICIS,VBANK,업무자동화,NaT
10616,1004042,172.0,203530.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 반복 업무 자동화,업무생산성,올인원,2021-04-11 14:57:45,90000,[럭키룰렛] 올인원패키지,10000.0,100000.0,INICIS,VBANK,업무자동화,NaT
17344,1028841,172.0,202072.0,ORDER,COMPLETED,올인원 패키지 : 코딩 첫 걸음 프로젝트,프로그래밍,올인원,2021-04-26 00:20:35,7500,coupon_applied,90000.0,97500.0,INICIS,VBANK,코딩 입문,2020-01-23
17345,1028844,172.0,202072.0,PAYMENT,COMPLETED,올인원 패키지 : 코딩 첫 걸음 프로젝트,프로그래밍,올인원,2021-04-26 00:21:11,7500,4월 1+1 페이백 이벤트 쿠폰,90000.0,97500.0,INICIS,VBANK,코딩 입문,2020-01-23
28516,1062411,172.0,204631.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 node.js 웹 프로그래밍,프로그래밍,올인원,2021-05-10 13:18:17,69000,[럭키룰렛] 올인원패키지,10000.0,79000.0,INICIS,CARD,백엔드 개발,NaT
45572,1125119,172.0,202609.0,PAYMENT,COMPLETED,올인원 패키지 : 누구나 가능한 VR/AR 콘텐츠 제작,프로그래밍,올인원,2021-06-07 13:16:57,47500,5월 페이백 프로모션 쿠폰,69000.0,116500.0,INICIS,VBANK,게임,2020-05-21

In [ ]:
df[df['customer_id'] == 172.0]

,id,customer_id,course_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,pg,method,subcategory_title,marketing_start_at
10608,1004041,172.0,203530.0,ORDER,COMPLETED,초격차 패키지 : 한 번에 끝내는 반복 업무 자동화,업무생산성,올인원,2021-04-11 14:45:51,90000,coupon_applied,10000.0,100000.0,INICIS,VBANK,업무자동화,NaT
10616,1004042,172.0,203530.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 반복 업무 자동화,업무생산성,올인원,2021-04-11 14:57:45,90000,[럭키룰렛] 올인원패키지,10000.0,100000.0,INICIS,VBANK,업무자동화,NaT
17344,1028841,172.0,202072.0,ORDER,COMPLETED,올인원 패키지 : 코딩 첫 걸음 프로젝트,프로그래밍,올인원,2021-04-26 00:20:35,7500,coupon_applied,90000.0,97500.0,INICIS,VBANK,코딩 입문,2020-01-23
17345,1028844,172.0,202072.0,PAYMENT,COMPLETED,올인원 패키지 : 코딩 첫 걸음 프로젝트,프로그래밍,올인원,2021-04-26 00:21:11,7500,4월 1+1 페이백 이벤트 쿠폰,90000.0,97500.0,INICIS,VBANK,코딩 입문,2020-01-23
28516,1062411,172.0,204631.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 node.js 웹 프로그래밍,프로그래밍,올인원,2021-05-10 13:18:17,69000,[럭키룰렛] 올인원패키지,10000.0,79000.0,INICIS,CARD,백엔드 개발,NaT
45572,1125119,172.0,202609.0,PAYMENT,COMPLETED,올인원 패키지 : 누구나 가능한 VR/AR 콘텐츠 제작,프로그래밍,올인원,2021-06-07 13:16:57,47500,5월 페이백 프로모션 쿠폰,69000.0,116500.0,INICIS,VBANK,게임,2020-05-21

In [ ]:
# 해당의 정리된 내용을 엑셀로 저장
df.to_excel('/content/drive/MyDrive/offline6_FC_EDA/Teamraw.xlsx')

# 1차적으로 정리된 데이터를 통해서 실질적인 분석과 정리된 보고서로 이동
[\[offline6_FC_EDA\]Total code.ipynb](https://colab.research.google.com/drive/1rEWquegV0d9rbHX6IkRR2Ty7CsIlUFIH)